// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxb8Q8LDhjqUgKND4yMPGH7d6u-mfAVA',
    appId: '1:718513815057:web:d9c7fb8bc82c9f04c67bb0',
    messagingSenderId: '718513815057',
    projectId: 'agro-bharat-demo',
    authDomain: 'agro-bharat-demo.firebaseapp.com',
    storageBucket: 'agro-bharat-demo.appspot.com',
    measurementId: 'G-WGNXDXRWFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGfHHe6zR62pm31itjkxjjsUDnKVN9_vM',
    appId: '1:718513815057:android:982ed4c026726b93c67bb0',
    messagingSenderId: '718513815057',
    projectId: 'agro-bharat-demo',
    storageBucket: 'agro-bharat-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-fYSbFqERZ_bOHfEQ3Qje7XVgJpjicfs',
    appId: '1:718513815057:ios:8f9eb37b6ce51b68c67bb0',
    messagingSenderId: '718513815057',
    projectId: 'agro-bharat-demo',
    storageBucket: 'agro-bharat-demo.appspot.com',
    iosBundleId: 'labs.aim.agroBharat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-fYSbFqERZ_bOHfEQ3Qje7XVgJpjicfs',
    appId: '1:718513815057:ios:8f9eb37b6ce51b68c67bb0',
    messagingSenderId: '718513815057',
    projectId: 'agro-bharat-demo',
    storageBucket: 'agro-bharat-demo.appspot.com',
    iosBundleId: 'labs.aim.agroBharat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxb8Q8LDhjqUgKND4yMPGH7d6u-mfAVA',
    appId: '1:718513815057:web:c5640097c46f34afc67bb0',
    messagingSenderId: '718513815057',
    projectId: 'agro-bharat-demo',
    authDomain: 'agro-bharat-demo.firebaseapp.com',
    storageBucket: 'agro-bharat-demo.appspot.com',
    measurementId: 'G-T1DKL7KLB9',
  );
}
