// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsbOvyh-h5lWZKI_LAzCH9oo0brPpF5as',
    appId: '1:905020690253:web:f1da31870ecfa454557104',
    messagingSenderId: '905020690253',
    projectId: 'biofit-429421',
    authDomain: 'biofit-429421.firebaseapp.com',
    databaseURL: 'https://biofit-429421-default-rtdb.firebaseio.com',
    storageBucket: 'biofit-429421.appspot.com',
    measurementId: 'G-0RM6W3FSMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuVOwRnxF1gCzw0ESwIuYNCCNzBUEyLc',
    appId: '1:905020690253:android:d94b0b0f8219a8f5557104',
    messagingSenderId: '905020690253',
    projectId: 'biofit-429421',
    databaseURL: 'https://biofit-429421-default-rtdb.firebaseio.com',
    storageBucket: 'biofit-429421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFxjN4J0H8_4Ix57aWDD8PguonzR7qCU',
    appId: '1:905020690253:ios:7389ae40506a06a4557104',
    messagingSenderId: '905020690253',
    projectId: 'biofit-429421',
    databaseURL: 'https://biofit-429421-default-rtdb.firebaseio.com',
    storageBucket: 'biofit-429421.appspot.com',
    iosBundleId: 'labs.aim.agroBharat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuFxjN4J0H8_4Ix57aWDD8PguonzR7qCU',
    appId: '1:905020690253:ios:7389ae40506a06a4557104',
    messagingSenderId: '905020690253',
    projectId: 'biofit-429421',
    databaseURL: 'https://biofit-429421-default-rtdb.firebaseio.com',
    storageBucket: 'biofit-429421.appspot.com',
    iosBundleId: 'labs.aim.agroBharat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsbOvyh-h5lWZKI_LAzCH9oo0brPpF5as',
    appId: '1:905020690253:web:7b90a0fbd309a288557104',
    messagingSenderId: '905020690253',
    projectId: 'biofit-429421',
    authDomain: 'biofit-429421.firebaseapp.com',
    databaseURL: 'https://biofit-429421-default-rtdb.firebaseio.com',
    storageBucket: 'biofit-429421.appspot.com',
    measurementId: 'G-0PD76KPYFF',
  );
}
